stages:
  - build
  - push
  - deploy

build:
  stage: build
  only:
    - master
  tags:
    - api-gw
  script:
    - ls
    - echo APP_NAME=$APP_NAME >> .env
    - echo DEBUG_MODE=$DEBUG_MODE >> .env
    - echo RABBITMQ_HOST=$RABBITMQ_HOST >> .env
    - echo RABBITMQ_PORT=$RABBITMQ_PORT >> .env
    - echo RABBITMQ_USER=$RABBITMQ_USER >> .env
    - echo RABBITMQ_PASS=$RABBITMQ_PASS >> .env
    - echo UVICORN_HOST=$UVICORN_HOST >> .env
    - echo UVICORN_PORT=$UVICORN_PORT >> .env
    - echo TOKEN=$TOKEN >> .env
    - echo SENDER=$SENDER >> .env
    - echo RECIPIENTS=$RECIPIENTS >> .env
    - echo TEMPLATE=$TEMPLATE >> .env
    - echo GALLERY_DIR=$GALLERY_DIR >> .env
    - echo SECRET_KEY=$SECRET_KEY >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS 
    - docker build -t api-gateway:0.0.1 .

dev_deploy:
  stage: deploy
  only:
    - master
  tags:
    - api-gw
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo DEBUG_MODE=$DEBUG_MODE >> .env
    - echo RABBITMQ_HOST=$RABBITMQ_HOST >> .env
    - echo RABBITMQ_PORT=$RABBITMQ_PORT >> .env
    - echo RABBITMQ_USER=$RABBITMQ_USER >> .env
    - echo RABBITMQ_PASS=$RABBITMQ_PASS >> .env
    - echo UVICORN_HOST=$UVICORN_HOST >> .env
    - echo UVICORN_PORT=$UVICORN_PORT >> .env
    - echo TOKEN=$TOKEN >> .env
    - echo SENDER=$SENDER >> .env
    - echo RECIPIENTS=$RECIPIENTS >> .env
    - echo TEMPLATE=$TEMPLATE >> .env
    - echo GALLERY_DIR=$GALLERY_DIR >> .env
    - echo SECRET_KEY=$SECRET_KEY >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build --scale api=6

push:
  stage: push
  only:
    - dev
  tags:
    - deploy
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo DEBUG_MODE=1 >> .env
    - echo RABBITMQ_HOST="172.16.16.16" >> .env
    - echo RABBITMQ_PORT=$RABBITMQ_PORT >> .env
    - echo RABBITMQ_USER=$RABBITMQ_USER >> .env
    - echo RABBITMQ_PASS=$RABBITMQ_PASS >> .env
    - echo UVICORN_HOST=$UVICORN_HOST >> .env
    - echo UVICORN_PORT=$UVICORN_PORT >> .env
    - echo TOKEN=$TOKEN >> .env
    - echo SENDER=$SENDER >> .env
    - echo RECIPIENTS=$RECIPIENTS >> .env
    - echo TEMPLATE=$TEMPLATE >> .env
    - echo GALLERY_DIR=$GALLERY_DIR >> .env
    - echo SECRET_KEY=$SECRET_KEY >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker build -t api-gateway:0.0.1 . #-t nexus.aasood.com/backend/web-api-gateway:$CI_COMMIT_SHORT_SHA
#    - docker push nexus.aasood.com/backend/web-api-gateway:$CI_COMMIT_SHORT_SHA

master_deploy:
  stage: deploy
  only:
    - dev
  tags:
    - deploy
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo DEBUG_MODE=1 >> .env
    - echo RABBITMQ_HOST="172.16.16.16" >> .env
    - echo RABBITMQ_PORT=$RABBITMQ_PORT >> .env
    - echo RABBITMQ_USER=$RABBITMQ_USER >> .env
    - echo RABBITMQ_PASS=$RABBITMQ_PASS >> .env
    - echo UVICORN_HOST=$UVICORN_HOST >> .env
    - echo UVICORN_PORT=$UVICORN_PORT >> .env
    - echo TOKEN=$TOKEN >> .env
    - echo SENDER=$SENDER >> .env
    - echo RECIPIENTS=$RECIPIENTS >> .env
    - echo TEMPLATE=$TEMPLATE >> .env
    - echo GALLERY_DIR=$GALLERY_DIR >> .env
    - echo SECRET_KEY=$SECRET_KEY >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build --scale api=4
masood_deploy:
  stage: deploy
  only:
    - maaaasd
  tags:
    - api-gw
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo DEBUG_MODE=$DEBUG_MODE >> .env
    - echo RABBITMQ_HOST=$RABBITMQ_HOST >> .env
    - echo RABBITMQ_PORT=$RABBITMQ_PORT >> .env
    - echo RABBITMQ_USER=$RABBITMQ_USER >> .env
    - echo RABBITMQ_PASS=$RABBITMQ_PASS >> .env
    - echo UVICORN_HOST=$UVICORN_HOST >> .env
    - echo UVICORN_PORT=$UVICORN_PORT >> .env
    - echo TOKEN=$TOKEN >> .env
    - echo SENDER=$SENDER >> .env
    - echo RECIPIENTS=$RECIPIENTS >> .env
    - echo TEMPLATE=$TEMPLATE >> .env
    - echo GALLERY_DIR=$GALLERY_DIR >> .env
    - echo SECRET_KEY=$SECRET_KEY >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build --scale api=4
