stages:
  - build
  - push
  - deploy


build:
  stage: build
  only:
    - temp
  tags:
    - pay
  script:
    - ls
    - echo APP_NAME=$APP_NAME >> .env
    - echo DEBUG_MODE=$DEBUG_MODE >> .env
    - echo RABBITMQ_HOST=$RABBITMQ_HOST >> .env
    - echo RABBITMQ_PORT=$RABBITMQ_PORT >> .env
    - echo RABBITMQ_USER=$RABBITMQ_USER >> .env
    - echo RABBITMQ_PASS=$RABBITMQ_PASS >> .env
    - echo UVICORN_HOST=$UVICORN_HOST >> .env
    - echo UVICORN_PORT=$UVICORN_PORT >> .env
    - echo TOKEN=$TOKEN >> .env
    - echo SENDER=$SENDER >> .env
    - echo RECIPIENTS=$RECIPIENTS >> .env
    - echo TEMPLATE=$TEMPLATE >> .env
    - echo GALLERY_DIR=$GALLERY_DIR >> .env
    - docker login 200.100.100.219:80 -u registry -p $REGPASS 
    - docker build -t api-gateway:0.0.1 .

dev_deploy:
  stage: deploy
  only:
    - temp
  tags:
    - pay
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo DEBUG_MODE=$DEBUG_MODE >> .env
    - echo RABBITMQ_HOST=$RABBITMQ_HOST >> .env
    - echo RABBITMQ_PORT=$RABBITMQ_PORT >> .env
    - echo RABBITMQ_USER=$RABBITMQ_USER >> .env
    - echo RABBITMQ_PASS=$RABBITMQ_PASS >> .env
    - echo UVICORN_HOST=$UVICORN_HOST >> .env
    - echo UVICORN_PORT=$UVICORN_PORT >> .env
    - echo TOKEN=$TOKEN >> .env
    - echo SENDER=$SENDER >> .env
    - echo RECIPIENTS=$RECIPIENTS >> .env
    - echo TEMPLATE=$TEMPLATE >> .env
    - echo GALLERY_DIR=$GALLERY_DIR >> .env
    - docker login 200.100.100.219:80 -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build

push:
  stage: push
  only:
    - master
  tags:
    - pay
  script:
    - docker login 200.100.100.219:80 -u registry -p $REGPASS
    - docker build -t api-gateway:0.0.1 . -t 200.100.100.219:80/backend/web-api-gateway:$CI_COMMIT_SHORT_SHA
    - docker push 200.100.100.219:80/backend/web-api-gateway:$CI_COMMIT_SHORT_SHA

master_deploy:
  stage: deploy
  only:
    - master
  tags:
    - pay
  script:
    - docker login 200.100.100.219:80 -u registry -p $REGPASS
    - docker run -p 8000:80 api-gateway:0.0.1
