version: "2"

services:
    web:
        build: nginx
        expose:
          - 80
        ports:
          - 8080:80
          - 4433:443
        depends_on:
          - api
        networks:
          - apinet

    api:
        resources:
        limits:
          cpus: '5.5'
          memory: 16384M
        reservations:
          cpus: '2.5'
          memory: 8096M
        build: .
        ports:
          - 8000:80
          - 8075:8008
        volumes:
          - /gallery-files:/gallery-files
          - /home/masood/logs/api-gateway:/api-gateway/log
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro


networks:
    apinet:
        driver: bridge


