version: "3"

services:
    web:
        build: nginx
        ports:
          - 80:80
          - 443:443
        depends_on:
          - api
        networks:
            - api-gw-net


    api:
        build: .
        ports:
          - 8000:80
        volumes:
          - /gallery-files:/gallery-files

api-gw-net:
        driver: bridge

