version: "3"

services:
    web:
        build: nginx
        expose:
          - 80
        ports:
          - 8080:80
          - 4433:443
        depends_on:
          - api
        networks:
          - apinet

    api:
        build: .
        ports:
          - 8000:80
          - 8075:8008
        volumes:
          - /gallery-files:/gallery-files
          - /home/masood/logs/api-gateway:/api-gateway/log
        environment:
        - TZ=Asia/Tehran


networks:
    apinet:
        driver: bridge


