version: "3"

services:
    web:
        build: nginx
        ports:
          - 8080:80
          - 4433:443
        depends_on:
          - api

    api:
        build: .
        ports:
          - 8000:8080
        volumes:
          - /gallery-files:/gallery-files
