version: "3"

services:
  nginx:
    build: ./nginx
    container_name: api-nginx
    ports:
      - "80:80"
    networks:
      - apinet
    depends_on:
      - api
  api:
    build: .
    volumes:
      - /gallery-files:/gallery-files
      - /home/masood/logs/api-gateway:/api-gateway/log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "8000"
    networks:
      - apinet
networks:
    apinet:
        driver: bridge
