version: "3"

services:
    web:
        build: nginx
        expose:
          - 80
        depends_on:
          - api
        networks:
          - apinet


    api:
        build: .
        ports:
          - 8000:80
        volumes:
          - /gallery-files:/gallery-files

networks:
    apinet:
        driver: bridge

