version: "3"

services:
    zabix:
      image: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      networks:
        - rabbitmq_net
    
    web:
        build: nginx
        ports:
          - 80:80
          - 443:443
        depends_on:
          - api

    api:
        build: .
        ports:
          - 8000:80

networks:
  rabbitmq_net:
    driver: bridge
